module.exports = {
  created_at: "Tue Jan 03 10:58:22 +0000 2023",
  id: 1610229074399531000,
  id_str: "1610229074399531009",
  text:
    "It is true that wahala no deh finish, but Miracle no deh tire Jesus\n" +
    "\n" +
    "#miraclenodeytirejesus \n" +
    "#cherishayo... https://t.co/mGYlik8xIx",
  truncated: true,
  entities: {
    hashtags: [[Object], [Object]],
    symbols: [],
    user_mentions: [],
    urls: [[Object]],
  },
  metadata: { iso_language_code: "en", result_type: "recent" },
  source:
    '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 125094752,
    id_str: "125094752",
    name: "Cherish Ayo",
    screen_name: "Cherish_Ayo",
    location: "Nigeria-Lagos",
    description:
      "Passionate about Helping people live according to the creator's design... //Pastor @thelogicchurch",
    url: null,
    entities: { description: [Object] },
    protected: false,
    followers_count: 537,
    friends_count: 549,
    listed_count: 6,
    created_at: "Sun Mar 21 17:28:16 +0000 2010",
    favourites_count: 203,
    utc_offset: null,
    time_zone: null,
    geo_enabled: true,
    verified: false,
    statuses_count: 1506,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: "C0DEED",
    profile_background_image_url:
      "http://abs.twimg.com/images/themes/theme1/bg.png",
    profile_background_image_url_https:
      "https://abs.twimg.com/images/themes/theme1/bg.png",
    profile_background_tile: false,
    profile_image_url:
      "http://pbs.twimg.com/profile_images/1592218767697797121/-wGlJVau_normal.jpg",
    profile_image_url_https:
      "https://pbs.twimg.com/profile_images/1592218767697797121/-wGlJVau_normal.jpg",
    profile_banner_url:
      "https://pbs.twimg.com/profile_banners/125094752/1668449522",
    profile_link_color: "1DA1F2",
    profile_sidebar_border_color: "C0DEED",
    profile_sidebar_fill_color: "DDEEF6",
    profile_text_color: "333333",
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false,
    translator_type: "none",
    withheld_in_countries: [],
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: "en",
};
